-- AlterTable
ALTER TABLE `user` ADD COLUMN `bio` VARCHAR(191) NULL,
    ADD COLUMN `firstName` VARCHAR(191) NULL,
    ADD COLUMN `lastName` VARCHAR(191) NULL,
    ADD COLUMN `livingIn` VARCHAR(191) NULL,
    ADD COLUMN `wentTo` VARCHAR(191) NULL,
    ADD COLUMN `worksAt` VARCHAR(191) NULL;
